# Generated by Django 4.2 on 2023-08-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
